imagenet:
  dataset_name: 'imagenet'
#  for universal attack and single attack '/dt/shabtaia/dt-fujitsu/datasets/others/imagnet/ILSVRC/Data/DET/amit_use'
  root_path: '/dt/shabtaia/dt-fujitsu/datasets/others/imagnet/ILSVRC/Data/DET/amit_use'

coco:
  dataset_name: 'coco'
  root_path: '/dt/shabtaia/dt-fujitsu/datasets/image_captioning/coco2017/'



