imagenet:
  dataset_name: 'imagenet'
# for class universal attack - choose from the following: n01495701,n01531178, n01644900, n01688243, n06874185
  root_path: "/dt/shabtaia/dt-fujitsu/datasets/others/imagnet/ILSVRC/Data/DET/amit_use/images/train/n01495701/"



