imagenet:
  dataset_name: 'imagenet'
  root_path: '/dt/shabtaia/dt-fujitsu/datasets/active/imagenet_detection/'
  height: 270
  width: 480
  active_output_indices:
    x1: 60
    x2: -1
    y1: 62
    y2: -38

