VIT:
  model_path: 'google/vit-base-patch16-224'
  weights_path: 'add later'
  input_size: 1600
  output_size: 500

DeiT:
  model_path: 'facebook/deit-base-distilled-patch16-224'
  weights_path: 'add later'
  input_size: 1600
  output_size: 500

Detr:
  model_path: 'SenseTime/deformable-detr'
  weights_path: 'add later'
  input_size: 1600
  output_size: 500